### ISSUE TITLE
UnboundLocalError: local variable 'hash_value_x_t' referenced before assignment

### ISSUE THREAD

**Issue by 123alikaha** [groupJia/MedSharing2021#2]
Hello, your code in constant_abe.py the hash_value_x_t is not defined let if I suppose it is global then it returns the error that the hash_value_x_t is not defined so what are the actual codes here so it makes sense to run up the codes. 
```
def setup():
    global hash_value_x_t
    """
    Generates public key and master secret key.
    :return:
    """
    if debug:
        print('\nSetup algorithm:\n')
 
    params = Parameters(qbits=512, rbits=160)  # type a
    pairing = Pairing(params)
    # G2 generator g
    g = Element.random(pairing, G2)  # 1024 bytes
    # x y
    x_ran = Element.random(pairing, Zr)  # 160 bits
    y_ran = Element.random(pairing, Zr)
    c1='1'+str(hash_value_x_t)
    c2 ='2'+ str(hash_value_x_t)
    hash_value_x_t = Element.from_hash(pairing, Zr,c1)
    print('11', hash_value_x_t)
    hash_value_x_t = Element.from_hash(pairing, Zr, c2)
    print('22', hash_value_x_t)
 
    print(hash_value_x_t)
```
Error:
Traceback (most recent call last):
  File "/home/ali/Downloads/MedShare2021-main/constant_abe.py", line 231, in <module>
    (pk, msk) = setup()
  File "/home/ali/Downloads/MedShare2021-main/constant_abe.py", line 26, in setup
    c1='1'+str(hash_value_x_t)
NameError: name 'hash_value_x_t' is not defined

**Comment by Wujianting** [comment]
> Hello, your code in constant_abe.py the hash_value_x_t is not defined let if I suppose it is global then it returns the error that the hash_value_x_t is not defined so what are the actual codes here so it makes sense to run up the codes.
> 
> ```
> def setup():
>     global hash_value_x_t
>     """
>     Generates public key and master secret key.
>     :return:
>     """
>     if debug:
>         print('\nSetup algorithm:\n')
>  
>     params = Parameters(qbits=512, rbits=160)  # type a
>     pairing = Pairing(params)
>     # G2 generator g
>     g = Element.random(pairing, G2)  # 1024 bytes
>     # x y
>     x_ran = Element.random(pairing, Zr)  # 160 bits
>     y_ran = Element.random(pairing, Zr)
>     c1='1'+str(hash_value_x_t)
>     c2 ='2'+ str(hash_value_x_t)
>     hash_value_x_t = Element.from_hash(pairing, Zr,c1)
>     print('11', hash_value_x_t)
>     hash_value_x_t = Element.from_hash(pairing, Zr, c2)
>     print('22', hash_value_x_t)
>  
>     print(hash_value_x_t)
> ```
> 
> Error: Traceback (most recent call last): File "/home/ali/Downloads/MedShare2021-main/constant_abe.py", line 231, in (pk, msk) = setup() File "/home/ali/Downloads/MedShare2021-main/constant_abe.py", line 26, in setup c1='1'+str(hash_value_x_t) NameError: name 'hash_value_x_t' is not defined

Hello, I would like to ask if the code is missing some files at present? Do you know which documents are missing? Has your code run successfully?
你好，我想请问一下目前代码是缺少一些文件吗？具体缺少哪些文件您了解吗？您代码目前已经运行成功了吗？

**Comment by 123alikaha** [comment]
It looks like the error is caused maybe missing files of the dataset you use so far can you share it with me on my personal email address muqadarali14@yahoo.com in this regard it is better to contact me by email.
